### ISSUE TITLE
Optional fields in new review form still affect the averages in the model

### ISSUE THREAD

**Issue by ZeshanA** [HomeRateDev/HomeRate#1]
The fields in the new review form that are optional are **nullable** in the database, but they default to a value of 1 on the front-end. When the user doesn't interact with one of these optional fields, the value of that field shouldn't affect the model in any way, but currently counts as a "1 star" rating.

**Comment by ed741** [comment]
Optional star-ratings now appear blank on the review form and if no stars are set the database correctly #stores a null value. The rating is then ignored by the weighting system.
