### ISSUE TITLE
No verification of .ac.uk emails in sign-up flow

### ISSUE THREAD

**Issue by ZeshanA** [HomeRateDev/HomeRate#2]
Verifying .ac.uk emails is a critical component of the site's security and incentive structure. We should use an email API provider (e.g. SendGrid etc.) to send verification emails from a homerate.co.uk address.

**Comment by ed741** [comment]
Front-end validation - Entering a non .ac.uk email now creates a popup telling the user they must use a .ac.uk email,
Back-end validation - The Form validation will reject any email that does not end in .ac.uk
Email-Verification - In the Sign-up flow, user's are sent an Email-verification email to the .ac.uk they entered which contains a generated unlock code (as a clickable link) that updates their user account in the database to be 'active' and all access controlled pages require the account to be 'active' to be considered 'logged in'
